apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    app: my-app
  template: 
    metadata:
      name: my-pod 
      labels:
        app: my-app
    spec: 
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 

